"""
CyberShield AI
Professional Report Cover Page
"""

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, Spacer
from reportlab.lib.enums import TA_CENTER

def build_cover_page(story, report_info: dict):
    """
    Build the report cover page.
    """

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]
    heading.alignment = TA_CENTER

    normal = styles["BodyText"]
    normal.alignment = TA_CENTER

    story.append(
        Spacer(1, 80)
    )

    story.append(
        Paragraph(
            "CyberShield AI",
            title
        )
    )

    story.append(
        Spacer(1, 20)
    )

    story.append(
        Paragraph(
            "Enterprise Security Assessment Report",
            heading
        )
    )

    story.append(
        Spacer(1, 60)
    )

    story.append(
        Paragraph(
            f"<b>Target:</b> {report_info['target']}",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Generated:</b> {report_info['generated_at']}",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Risk Level:</b> {report_info['risk_level']}",
            normal
        )
    )

    story.append(
        Spacer(1, 100)
    )

    story.append(
        Paragraph(
            "<b>Classification:</b> Internal Use Only",
            heading
        )
    )

    story.append(
        Spacer(1, 150)
    )

    story.append(
        Paragraph(
            "Generated by CyberShield AI",
            normal
        )
    )

    story.append(
        Paragraph(
            "Version 1.0",
            normal
        )
    )

    story.append(
        Spacer(1, 30)
    )

    return story
